// Auto-generated by generate_levels.py. Do not edit manually.

import { LevelId } from './levels';
import defaultLevelRoom from '../../assets/levels/level1/room/room_bare.png';

import defaultLevelStickersticker001 from '../../assets/levels/level1/stickers/sticker_001.png';
import defaultLevelStickersticker002 from '../../assets/levels/level1/stickers/sticker_002.png';
import defaultLevelStickersticker003 from '../../assets/levels/level1/stickers/sticker_003.png';
import defaultLevelStickersticker004 from '../../assets/levels/level1/stickers/sticker_004.png';
import defaultLevelStickersticker005 from '../../assets/levels/level1/stickers/sticker_005.png';
import defaultLevelStickersticker006 from '../../assets/levels/level1/stickers/sticker_006.png';
import defaultLevelStickersticker007 from '../../assets/levels/level1/stickers/sticker_007.png';
import defaultLevelStickersticker008 from '../../assets/levels/level1/stickers/sticker_008.png';
import defaultLevelStickersticker009 from '../../assets/levels/level1/stickers/sticker_009.png';
import defaultLevelStickersticker010 from '../../assets/levels/level1/stickers/sticker_010.png';
import defaultLevelStickersticker011 from '../../assets/levels/level1/stickers/sticker_011.png';
import defaultLevelStickersticker012 from '../../assets/levels/level1/stickers/sticker_012.png';
import defaultLevelStickersticker013 from '../../assets/levels/level1/stickers/sticker_013.png';
import defaultLevelStickersticker014 from '../../assets/levels/level1/stickers/sticker_014.png';
import defaultLevelStickersticker015 from '../../assets/levels/level1/stickers/sticker_015.png';
import defaultLevelStickersticker016 from '../../assets/levels/level1/stickers/sticker_016.png';
import defaultLevelStickersticker017 from '../../assets/levels/level1/stickers/sticker_017.png';
import defaultLevelStickersticker018 from '../../assets/levels/level1/stickers/sticker_018.png';
import defaultLevelStickersticker019 from '../../assets/levels/level1/stickers/sticker_019.png';
import defaultLevelStickersticker020 from '../../assets/levels/level1/stickers/sticker_020.png';
import defaultLevelStickersticker021 from '../../assets/levels/level1/stickers/sticker_021.png';
import defaultLevelStickersticker022 from '../../assets/levels/level1/stickers/sticker_022.png';
import defaultLevelStickersticker023 from '../../assets/levels/level1/stickers/sticker_023.png';
import defaultLevelStickersticker024 from '../../assets/levels/level1/stickers/sticker_024.png';
import defaultLevelStickersticker025 from '../../assets/levels/level1/stickers/sticker_025.png';
import defaultLevelStickersticker026 from '../../assets/levels/level1/stickers/sticker_026.png';
import defaultLevelStickersticker027 from '../../assets/levels/level1/stickers/sticker_027.png';
import defaultLevelStickersticker028 from '../../assets/levels/level1/stickers/sticker_028.png';
import defaultLevelStickersticker029 from '../../assets/levels/level1/stickers/sticker_029.png';
import defaultLevelStickersticker030 from '../../assets/levels/level1/stickers/sticker_030.png';
import defaultLevelStickersticker031 from '../../assets/levels/level1/stickers/sticker_031.png';
import defaultLevelStickersticker032 from '../../assets/levels/level1/stickers/sticker_032.png';
import defaultLevelStickersticker033 from '../../assets/levels/level1/stickers/sticker_033.png';
import defaultLevelStickersticker034 from '../../assets/levels/level1/stickers/sticker_034.png';
import defaultLevelStickersticker035 from '../../assets/levels/level1/stickers/sticker_035.png';
import defaultLevelStickersticker036 from '../../assets/levels/level1/stickers/sticker_036.png';
import defaultLevelStickersticker037 from '../../assets/levels/level1/stickers/sticker_037.png';
import defaultLevelStickersticker038 from '../../assets/levels/level1/stickers/sticker_038.png';
import defaultLevelStickersticker039 from '../../assets/levels/level1/stickers/sticker_039.png';
import defaultLevelStickersticker040 from '../../assets/levels/level1/stickers/sticker_040.png';
import defaultLevelStickersticker041 from '../../assets/levels/level1/stickers/sticker_041.png';
import defaultLevelStickersticker042 from '../../assets/levels/level1/stickers/sticker_042.png';
import defaultLevelStickersticker043 from '../../assets/levels/level1/stickers/sticker_043.png';
import defaultLevelStickersticker044 from '../../assets/levels/level1/stickers/sticker_044.png';
import defaultLevelStickersticker045 from '../../assets/levels/level1/stickers/sticker_045.png';
import defaultLevelStickersticker046 from '../../assets/levels/level1/stickers/sticker_046.png';
import defaultLevelStickersticker047 from '../../assets/levels/level1/stickers/sticker_047.png';
import defaultLevelStickersticker048 from '../../assets/levels/level1/stickers/sticker_048.png';
import defaultLevelStickersticker049 from '../../assets/levels/level1/stickers/sticker_049.png';
import defaultLevelStickersticker050 from '../../assets/levels/level1/stickers/sticker_050.png';
import defaultLevelStickersticker051 from '../../assets/levels/level1/stickers/sticker_051.png';
import defaultLevelStickersticker052 from '../../assets/levels/level1/stickers/sticker_052.png';
import defaultLevelStickersticker053 from '../../assets/levels/level1/stickers/sticker_053.png';
import defaultLevelStickersticker054 from '../../assets/levels/level1/stickers/sticker_054.png';
import defaultLevelStickersticker055 from '../../assets/levels/level1/stickers/sticker_055.png';
import defaultLevelStickersticker056 from '../../assets/levels/level1/stickers/sticker_056.png';
import defaultLevelStickersticker057 from '../../assets/levels/level1/stickers/sticker_057.png';
import defaultLevelStickersticker058 from '../../assets/levels/level1/stickers/sticker_058.png';
import defaultLevelStickersticker059 from '../../assets/levels/level1/stickers/sticker_059.png';
import defaultLevelStickersticker060 from '../../assets/levels/level1/stickers/sticker_060.png';
import defaultLevelStickersticker061 from '../../assets/levels/level1/stickers/sticker_061.png';
import defaultLevelStickersticker062 from '../../assets/levels/level1/stickers/sticker_062.png';
import defaultLevelStickersticker063 from '../../assets/levels/level1/stickers/sticker_063.png';
import defaultLevelStickersticker064 from '../../assets/levels/level1/stickers/sticker_064.png';
import defaultLevelStickersticker065 from '../../assets/levels/level1/stickers/sticker_065.png';
import defaultLevelStickersticker066 from '../../assets/levels/level1/stickers/sticker_066.png';
import defaultLevelStickersticker067 from '../../assets/levels/level1/stickers/sticker_067.png';
import defaultLevelStickersticker068 from '../../assets/levels/level1/stickers/sticker_068.png';
import defaultLevelStickersticker069 from '../../assets/levels/level1/stickers/sticker_069.png';
import defaultLevelStickersticker070 from '../../assets/levels/level1/stickers/sticker_070.png';
import defaultLevelStickersticker071 from '../../assets/levels/level1/stickers/sticker_071.png';
import defaultLevelStickersticker072 from '../../assets/levels/level1/stickers/sticker_072.png';
import defaultLevelStickersticker073 from '../../assets/levels/level1/stickers/sticker_073.png';

export const defaultLevelId: LevelId = 'level1';

export const defaultRoomImage = defaultLevelRoom;

export const defaultStickerImages: Record<string, any> = {
  'sticker_001': defaultLevelStickersticker001,
  'sticker_002': defaultLevelStickersticker002,
  'sticker_003': defaultLevelStickersticker003,
  'sticker_004': defaultLevelStickersticker004,
  'sticker_005': defaultLevelStickersticker005,
  'sticker_006': defaultLevelStickersticker006,
  'sticker_007': defaultLevelStickersticker007,
  'sticker_008': defaultLevelStickersticker008,
  'sticker_009': defaultLevelStickersticker009,
  'sticker_010': defaultLevelStickersticker010,
  'sticker_011': defaultLevelStickersticker011,
  'sticker_012': defaultLevelStickersticker012,
  'sticker_013': defaultLevelStickersticker013,
  'sticker_014': defaultLevelStickersticker014,
  'sticker_015': defaultLevelStickersticker015,
  'sticker_016': defaultLevelStickersticker016,
  'sticker_017': defaultLevelStickersticker017,
  'sticker_018': defaultLevelStickersticker018,
  'sticker_019': defaultLevelStickersticker019,
  'sticker_020': defaultLevelStickersticker020,
  'sticker_021': defaultLevelStickersticker021,
  'sticker_022': defaultLevelStickersticker022,
  'sticker_023': defaultLevelStickersticker023,
  'sticker_024': defaultLevelStickersticker024,
  'sticker_025': defaultLevelStickersticker025,
  'sticker_026': defaultLevelStickersticker026,
  'sticker_027': defaultLevelStickersticker027,
  'sticker_028': defaultLevelStickersticker028,
  'sticker_029': defaultLevelStickersticker029,
  'sticker_030': defaultLevelStickersticker030,
  'sticker_031': defaultLevelStickersticker031,
  'sticker_032': defaultLevelStickersticker032,
  'sticker_033': defaultLevelStickersticker033,
  'sticker_034': defaultLevelStickersticker034,
  'sticker_035': defaultLevelStickersticker035,
  'sticker_036': defaultLevelStickersticker036,
  'sticker_037': defaultLevelStickersticker037,
  'sticker_038': defaultLevelStickersticker038,
  'sticker_039': defaultLevelStickersticker039,
  'sticker_040': defaultLevelStickersticker040,
  'sticker_041': defaultLevelStickersticker041,
  'sticker_042': defaultLevelStickersticker042,
  'sticker_043': defaultLevelStickersticker043,
  'sticker_044': defaultLevelStickersticker044,
  'sticker_045': defaultLevelStickersticker045,
  'sticker_046': defaultLevelStickersticker046,
  'sticker_047': defaultLevelStickersticker047,
  'sticker_048': defaultLevelStickersticker048,
  'sticker_049': defaultLevelStickersticker049,
  'sticker_050': defaultLevelStickersticker050,
  'sticker_051': defaultLevelStickersticker051,
  'sticker_052': defaultLevelStickersticker052,
  'sticker_053': defaultLevelStickersticker053,
  'sticker_054': defaultLevelStickersticker054,
  'sticker_055': defaultLevelStickersticker055,
  'sticker_056': defaultLevelStickersticker056,
  'sticker_057': defaultLevelStickersticker057,
  'sticker_058': defaultLevelStickersticker058,
  'sticker_059': defaultLevelStickersticker059,
  'sticker_060': defaultLevelStickersticker060,
  'sticker_061': defaultLevelStickersticker061,
  'sticker_062': defaultLevelStickersticker062,
  'sticker_063': defaultLevelStickersticker063,
  'sticker_064': defaultLevelStickersticker064,
  'sticker_065': defaultLevelStickersticker065,
  'sticker_066': defaultLevelStickersticker066,
  'sticker_067': defaultLevelStickersticker067,
  'sticker_068': defaultLevelStickersticker068,
  'sticker_069': defaultLevelStickersticker069,
  'sticker_070': defaultLevelStickersticker070,
  'sticker_071': defaultLevelStickersticker071,
  'sticker_072': defaultLevelStickersticker072,
  'sticker_073': defaultLevelStickersticker073,
};

export const defaultLevelData = {
  levelId: 'level1' as LevelId,
  room: 'level1',
  bgImage: defaultLevelRoom,
  bgSize: {"width": 557, "height": 634},
  items: [
    {
      id: 'sticker_073',
      uri: defaultLevelStickersticker073,
      normX: 0.11087486864592877,
      normY: 0.32660699272021426,
      scale: 1.7000000000000006,
      rotation: 0,
      rotation3D: 0,
      layer: 1,
      uid: 'sticker_073_0',
    },
    {
      id: 'sticker_071',
      uri: defaultLevelStickersticker071,
      normX: 0.5000239045263312,
      normY: 0.7392607026699773,
      scale: 2.200000000000001,
      rotation: 0,
      rotation3D: 0,
      layer: 2,
      uid: 'sticker_071_0',
    },
    {
      id: 'sticker_038',
      uri: defaultLevelStickersticker038,
      normX: 0.12027693706968957,
      normY: 0.460905418713343,
      scale: 1,
      rotation: 0,
      rotation3D: 0,
      layer: 50,
      uid: 'sticker_038_0',
    },
    {
      id: 'sticker_021',
      uri: defaultLevelStickersticker021,
      normX: 0.8498040625059572,
      normY: 0.43361952396076076,
      scale: 4.300000000000002,
      rotation: 0,
      rotation3D: 0,
      layer: 5,
      uid: 'sticker_021_0',
    },
    {
      id: 'sticker_020',
      uri: defaultLevelStickersticker020,
      normX: 0.20531590654132334,
      normY: 0.5013357925470934,
      scale: 2.9742187500000004,
      rotation: 0,
      rotation3D: 0,
      layer: 6,
      uid: 'sticker_020_0',
    },
    {
      id: 'sticker_001',
      uri: defaultLevelStickersticker001,
      normX: 0.4729713848581754,
      normY: 0.3122614417712063,
      scale: 5,
      rotation: 0,
      rotation3D: 0,
      layer: 1,
      uid: 'sticker_001_0',
    },
    {
      id: 'sticker_034',
      uri: defaultLevelStickersticker034,
      normX: 0.6636596760481029,
      normY: 0.6332978472301846,
      scale: 3.6000000000000023,
      rotation: 0,
      rotation3D: 0,
      layer: 21,
      uid: 'sticker_034_0',
    },
  ],
};
