// Auto-generated by generate_levels.py. Do not edit manually.

import level1Data from '../../assets/levels/level1.json';
import level2Data from '../../assets/levels/level2.json';

import level1Room from '../../assets/levels/level1/room/room_bare.png';
import level2Room from '../../assets/levels/level2/room/room_bare.png';

import level1Stickersticker004 from '../../assets/levels/level1/stickers/sticker_004.png';
import level1Stickersticker006 from '../../assets/levels/level1/stickers/sticker_006.png';
import level1Stickersticker012 from '../../assets/levels/level1/stickers/sticker_012.png';
import level1Stickersticker018 from '../../assets/levels/level1/stickers/sticker_018.png';
import level1Stickersticker025 from '../../assets/levels/level1/stickers/sticker_025.png';
import level1Stickersticker033 from '../../assets/levels/level1/stickers/sticker_033.png';
import level1Stickersticker049 from '../../assets/levels/level1/stickers/sticker_049.png';
import level1Stickersticker052 from '../../assets/levels/level1/stickers/sticker_052.png';
import level1Stickersticker062 from '../../assets/levels/level1/stickers/sticker_062.png';
import level1Stickersticker069 from '../../assets/levels/level1/stickers/sticker_069.png';
import level1Stickersticker072 from '../../assets/levels/level1/stickers/sticker_072.png';
import level2Stickersticker013 from '../../assets/levels/level2/stickers/sticker_013.png';
import level2Stickersticker016 from '../../assets/levels/level2/stickers/sticker_016.png';
import level2Stickersticker021 from '../../assets/levels/level2/stickers/sticker_021.png';
import level2Stickersticker023 from '../../assets/levels/level2/stickers/sticker_023.png';
import level2Stickersticker024 from '../../assets/levels/level2/stickers/sticker_024.png';
import level2Stickersticker026 from '../../assets/levels/level2/stickers/sticker_026.png';
import level2Stickersticker028 from '../../assets/levels/level2/stickers/sticker_028.png';
import level2Stickersticker036 from '../../assets/levels/level2/stickers/sticker_036.png';
import level2Stickersticker037 from '../../assets/levels/level2/stickers/sticker_037.png';
import level2Stickersticker042 from '../../assets/levels/level2/stickers/sticker_042.png';
import level2Stickersticker043 from '../../assets/levels/level2/stickers/sticker_043.png';
import level2Stickersticker046 from '../../assets/levels/level2/stickers/sticker_046.png';
import level2Stickersticker056 from '../../assets/levels/level2/stickers/sticker_056.png';
import level2Stickersticker058 from '../../assets/levels/level2/stickers/sticker_058.png';
import level2Stickersticker060 from '../../assets/levels/level2/stickers/sticker_060.png';
import level2Stickersticker062 from '../../assets/levels/level2/stickers/sticker_062.png';
import level2Stickersticker066 from '../../assets/levels/level2/stickers/sticker_066.png';
import level2Stickersticker068 from '../../assets/levels/level2/stickers/sticker_068.png';
import level2Stickersticker069 from '../../assets/levels/level2/stickers/sticker_069.png';
import level2Stickersticker075 from '../../assets/levels/level2/stickers/sticker_075.png';
import level2Stickersticker077 from '../../assets/levels/level2/stickers/sticker_077.png';
import level2Stickersticker079 from '../../assets/levels/level2/stickers/sticker_079.png';
import level2Stickersticker083 from '../../assets/levels/level2/stickers/sticker_083.png';
import level2Stickersticker084 from '../../assets/levels/level2/stickers/sticker_084.png';
import level2Stickersticker085 from '../../assets/levels/level2/stickers/sticker_085.png';
import level2Stickersticker088 from '../../assets/levels/level2/stickers/sticker_088.png';
import level2Stickersticker089 from '../../assets/levels/level2/stickers/sticker_089.png';
import level2Stickersticker090 from '../../assets/levels/level2/stickers/sticker_090.png';
import level2Stickersticker092 from '../../assets/levels/level2/stickers/sticker_092.png';
import level2Stickersticker093 from '../../assets/levels/level2/stickers/sticker_093.png';
import level2Stickersticker095 from '../../assets/levels/level2/stickers/sticker_095.png';
import level2Stickersticker097 from '../../assets/levels/level2/stickers/sticker_097.png';

export type LevelId = 'level1' | 'level2';

export type Level = {
  id: LevelId;
  name: string;
  data: any;
  roomImage: any;
  stickerImages: Record<string, any>;
};

export const LEVELS: Level[] = [
  {
    id: 'level1',
    name: 'Level 1',
    data: level1Data,
    roomImage: level1Room,
    stickerImages: {
    'sticker_004': level1Stickersticker004,
    'sticker_006': level1Stickersticker006,
    'sticker_012': level1Stickersticker012,
    'sticker_018': level1Stickersticker018,
    'sticker_025': level1Stickersticker025,
    'sticker_033': level1Stickersticker033,
    'sticker_049': level1Stickersticker049,
    'sticker_052': level1Stickersticker052,
    'sticker_062': level1Stickersticker062,
    'sticker_069': level1Stickersticker069,
    'sticker_072': level1Stickersticker072,
    },
  },
  {
    id: 'level2',
    name: 'Level 2',
    data: level2Data,
    roomImage: level2Room,
    stickerImages: {
    'sticker_013': level2Stickersticker013,
    'sticker_016': level2Stickersticker016,
    'sticker_021': level2Stickersticker021,
    'sticker_023': level2Stickersticker023,
    'sticker_024': level2Stickersticker024,
    'sticker_026': level2Stickersticker026,
    'sticker_028': level2Stickersticker028,
    'sticker_036': level2Stickersticker036,
    'sticker_037': level2Stickersticker037,
    'sticker_042': level2Stickersticker042,
    'sticker_043': level2Stickersticker043,
    'sticker_046': level2Stickersticker046,
    'sticker_056': level2Stickersticker056,
    'sticker_058': level2Stickersticker058,
    'sticker_060': level2Stickersticker060,
    'sticker_062': level2Stickersticker062,
    'sticker_066': level2Stickersticker066,
    'sticker_068': level2Stickersticker068,
    'sticker_069': level2Stickersticker069,
    'sticker_075': level2Stickersticker075,
    'sticker_077': level2Stickersticker077,
    'sticker_079': level2Stickersticker079,
    'sticker_083': level2Stickersticker083,
    'sticker_084': level2Stickersticker084,
    'sticker_085': level2Stickersticker085,
    'sticker_088': level2Stickersticker088,
    'sticker_089': level2Stickersticker089,
    'sticker_090': level2Stickersticker090,
    'sticker_092': level2Stickersticker092,
    'sticker_093': level2Stickersticker093,
    'sticker_095': level2Stickersticker095,
    'sticker_097': level2Stickersticker097,
    },
  },
];

export function getLevelById(id: LevelId): Level | undefined {
  return LEVELS.find(level => level.id === id);
}
